#version: '3'

# name: "ps-web-${TAG}"

networks:
  default:
    name: "${NETWORK}"
    external: true

services:
  web:
    build: .
    image: "ps-web-${TAG}"
    environment:
      APP_ENV: "${APP_ENV}"
      APP_VERSION: "${TAG}"
      APP_URL: "${APP_URL}"
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      DATABASE_URL: "${DATABASE_URL}"
      MAILER_DSN: "${MAILER_DSN}"
      MESSENGER_TRANSPORT_DSN: "${MESSENGER_TRANSPORT_DSN}"
      JSON_HUB_PROJECT: "${JSON_HUB_PROJECT}"
      MAILING_PROVIDER_ROUTING_KEY: "${MAILING_PROVIDER_ROUTING_KEY}"

  worker:
    image: "ps-web-${TAG}"
    restart: always
    environment:
      APP_ENV: "${APP_ENV}"
      APP_URL: "${APP_URL}"
      DATABASE_URL: "${DATABASE_URL}"
      MAILER_DSN: "${MAILER_DSN}"
    command:
      - 'bin/console'
      - 'messenger:consume'
      - 'async'
      - '--memory-limit=110M'
      - '--time-limit=3600'
      - '--limit=100'
      - '-vv'
    depends_on:
      - web

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
